import React, { useState } from 'react';
import { 
  Sun, 
  Battery, 
  DollarSign, 
  TrendingUp, 
  ArrowRight, 
  Calculator,
  Zap,
  Leaf,
  ShieldCheck
} from 'lucide-react';
import { useLanguage } from '../../lib/i18n';

export function HeroCalculator() {
  const { language } = useLanguage();
  
  // Model state: 'opex' (RESCO - zero investment) vs 'capex' (ownership)
  const [model, setModel] = useState<'opex' | 'capex'>('opex');
  
  // Inputs
  const [monthlyBill, setMonthlyBill] = useState(25000); // in BDT
  const [solarProductionRatio, setSolarProductionRatio] = useState(0.85); // 85% default
  
  // Real Locked Operational Constants (Taz's Operating Doctrine)
  const gridRate = 10.30; // BDT/kWh (LT-E utility rate)
  const opexTariff = 7.00; // BDT/kWh (Netso customer tariff, 32% discount)
  const capexRate = 90000; // BDT/kWp (CAPEX cost including engineering)
  const annualYieldPerKwp = 1400; // kWh produced annually per 1 kWp installed in Dhaka
  const carbonOffsetFactor = 0.62; // kg CO2 saved per kWh
  const treeAbsorptionFactor = 22; // kg CO2 absorbed per tree per year

  // Calculated Sizing Metrics
  // Monthly Energy Consumption (kWh) = Monthly Bill / Grid Rate
  const monthlyConsumptionKwh = monthlyBill / gridRate;
  const annualConsumptionKwh = monthlyConsumptionKwh * 12;
  
  // Targeted solar production (kWh/year)
  const targetAnnualSolarKwh = annualConsumptionKwh * solarProductionRatio;
  
  // System Size (kWp) needed to produce that amount of energy
  const systemSize = targetAnnualSolarKwh / annualYieldPerKwp;
  
  // Financial Metrics
  const totalCapex = systemSize * capexRate;
  const monthlySolarGenerationKwh = (targetAnnualSolarKwh / 12);
  
  // Savings calculation:
  // Under OPEX: save (gridRate - opexTariff) per kWh generated by solar
  // Under CAPEX: save gridRate per kWh generated by solar (offsetting utility cost completely)
  const monthlySavings = model === 'opex' 
    ? monthlySolarGenerationKwh * (gridRate - opexTariff)
    : monthlySolarGenerationKwh * gridRate;

  const annualSavings = monthlySavings * 12;
  const paybackYears = model === 'opex' ? 0 : totalCapex / annualSavings;

  // Environmental Metrics
  const annualCarbonOffset = targetAnnualSolarKwh * carbonOffsetFactor;
  const equivalentTrees = annualCarbonOffset / treeAbsorptionFactor;

  return (
    <div className="w-full max-w-4xl mx-auto rounded-3xl border border-[#DCD6CD] bg-[#F5F2EB]/90 backdrop-blur-xl p-6 md:p-8 shadow-2xl relative overflow-hidden group">
      {/* Dynamic gradients */}
      <div className="absolute top-0 right-0 w-96 h-96 bg-primary/5 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none group-hover:bg-primary/8 transition-colors duration-700" />
      <div className="absolute bottom-0 left-0 w-96 h-96 bg-accent/5 rounded-full blur-3xl -ml-20 -mb-20 pointer-events-none" />
      
      <div className="relative z-10 grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* Inputs Column */}
        <div className="lg:col-span-7 space-y-6">
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <div className="p-2 rounded-xl bg-primary/10 text-primary">
                <Calculator className="w-5 h-5" />
              </div>
              <h3 className="text-2xl font-bold tracking-tight text-[#1F1914] font-aeonik">
                {language === 'en' ? 'Solar Savings Calculator' : 'সোলার সাশ্রয় ক্যালকুলেটর'}
              </h3>
            </div>
            <p className="text-sm text-[#5C544D]">
              {language === 'en' 
                ? 'Estimate solar sizing and check real utility economics tailored for Bangladesh.' 
                 : 'বাস্তবধর্মী ইউটিলিটি ইকোনমিক্স ও নিখুঁত সোলার সাইজিং তাৎক্ষণিকভাবে হিসেব করুন।'}
            </p>
          </div>

          {/* Model Toggle: OPEX (RESCO) vs CAPEX */}
          <div className="bg-[#E6E1D8]/60 p-1.5 rounded-2xl flex gap-1 border border-[#DCD6CD]">
            <button 
              onClick={() => setModel('opex')}
              className={`flex-1 py-3 px-4 rounded-xl text-xs font-bold transition-all duration-300 flex items-center justify-center gap-2 ${
                model === 'opex' 
                  ? 'bg-primary text-primary-foreground shadow-md' 
                  : 'text-[#5C544D] hover:bg-[#FAF8F5]/50'
              }`}
            >
              <Zap className="w-3.5 h-3.5" />
              <div className="text-left">
                <span className="block font-bold">OPEX (Zero-CAPEX RESCO)</span>
                <span className="block text-[10px] opacity-80 font-medium">
                  {language === 'en' ? 'No Investment, Pay per kWh' : 'বিনিয়োগহীন, প্রতি ইউনিট হিসেবে পে'}
                </span>
              </div>
            </button>
            <button 
              onClick={() => setModel('capex')}
              className={`flex-1 py-3 px-4 rounded-xl text-xs font-bold transition-all duration-300 flex items-center justify-center gap-2 ${
                model === 'capex' 
                  ? 'bg-primary text-primary-foreground shadow-md' 
                  : 'text-[#5C544D] hover:bg-[#FAF8F5]/50'
              }`}
            >
              <ShieldCheck className="w-3.5 h-3.5" />
              <div className="text-left">
                <span className="block font-bold">CAPEX (Purchase Model)</span>
                <span className="block text-[10px] opacity-80 font-medium">
                  {language === 'en' ? 'Full Ownership & Max Savings' : '১০০% মালিকানা ও সর্বোচ্চ সাশ্রয়'}
                </span>
              </div>
            </button>
          </div>

          {/* Input: Monthly Bill */}
          <div className="space-y-3 bg-[#FAF8F5]/50 p-4 rounded-2xl border border-[#DCD6CD]/50">
            <div className="flex justify-between items-center">
              <label htmlFor="monthly-bill-range" className="text-sm font-bold text-[#1F1914]">
                {language === 'en' ? 'Monthly Electricity Bill' : 'মাসিক বিদ্যুৎ বিল'}
              </label>
              <span className="text-lg font-bold text-primary font-mono bg-[#E6E1D8]/40 px-3 py-1 rounded-lg">
                ৳{monthlyBill.toLocaleString()}
              </span>
            </div>
            <input 
              id="monthly-bill-range"
              type="range" 
              min="5000" 
              max="200000" 
              step="5000"
              value={monthlyBill}
              onChange={(e) => setMonthlyBill(Number(e.target.value))}
              className="w-full h-2 rounded-lg appearance-none cursor-pointer bg-[#E6E1D8] accent-primary"
            />
            <div className="flex justify-between text-xs text-[#8C837A] font-mono">
              <span>৳5,000</span>
              <span>৳200,000+</span>
            </div>
          </div>

          {/* Input: Solar Production Ratio */}
          <div className="space-y-3 bg-[#FAF8F5]/50 p-4 rounded-2xl border border-[#DCD6CD]/50">
            <div className="flex justify-between items-center">
              <label htmlFor="solar-ratio-range" className="text-sm font-bold text-[#1F1914]">
                {language === 'en' ? 'Target Energy Coverage' : 'টার্গেট এনার্জি কাভারেজ'}
              </label>
              <span className="text-lg font-bold text-primary font-mono bg-[#E6E1D8]/40 px-3 py-1 rounded-lg">
                {Math.round(solarProductionRatio * 100)}%
              </span>
            </div>
            <input 
              id="solar-ratio-range"
              type="range" 
              min="0.4" 
              max="1.0" 
              step="0.05"
              value={solarProductionRatio}
              onChange={(e) => setSolarProductionRatio(Number(e.target.value))}
              className="w-full h-2 rounded-lg appearance-none cursor-pointer bg-[#E6E1D8] accent-primary"
            />
            <div className="flex justify-between text-xs text-[#8C837A] font-mono">
              <span>40%</span>
              <span>100% {language === 'en' ? 'Net-Metered Offset' : 'নেট-মিটারড অফসেট'}</span>
            </div>
          </div>
        </div>

        {/* Results Column */}
        <div className="lg:col-span-5 bg-[#FAF8F5] rounded-2xl border border-[#DCD6CD] p-6 space-y-6 shadow-sm relative overflow-hidden">
          <div className="flex justify-between items-center pb-2 border-b border-[#E6E1D8]">
            <h4 className="text-xs font-bold text-[#8C837A] tracking-wider uppercase">
              {language === 'en' ? 'Economic Projection' : 'অর্থনৈতিক প্রক্ষেপণ'}
            </h4>
            <span className="text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full bg-primary/10 text-primary">
              {model.toUpperCase()}
            </span>
          </div>

          <div className="space-y-4">
            {/* Required System Size */}
            <div className="flex items-center justify-between pb-3 border-b border-[#E6E1D8]">
              <div className="flex items-center gap-2 text-sm text-[#5C544D]">
                <Sun className="w-4.5 h-4.5 text-amber-500" />
                <span>{language === 'en' ? 'Required System Size' : 'প্রয়োজনীয় সিস্টেম সাইজ'}</span>
              </div>
              <span className="text-lg font-bold text-[#1F1914] font-mono">
                {systemSize.toFixed(1)} kWp
              </span>
            </div>

            {/* Investment cost (Capex) */}
            <div className="flex items-center justify-between pb-3 border-b border-[#E6E1D8]">
              <div className="flex items-center gap-2 text-sm text-[#5C544D]">
                <DollarSign className="w-4.5 h-4.5 text-emerald-600" />
                <span>{language === 'en' ? 'Capital Investment' : 'মূলধনী বিনিয়োগ'}</span>
              </div>
              <span className="text-lg font-bold text-[#1F1914] font-mono">
                {model === 'opex' ? (
                  <span className="text-emerald-600 font-bold uppercase tracking-wider">৳0 (Free RESCO)</span>
                ) : (
                  `৳${Math.round(totalCapex).toLocaleString()}`
                )}
              </span>
            </div>

            {/* Monthly Savings */}
            <div className="flex items-center justify-between pb-3 border-b border-[#E6E1D8]">
              <div className="flex items-center gap-2 text-sm text-[#5C544D]">
                <TrendingUp className="w-4.5 h-4.5 text-primary" />
                <span>{language === 'en' ? 'Est. Monthly Savings' : 'অনুমিত মাসিক সাশ্রয়'}</span>
              </div>
              <span className="text-lg font-bold text-primary font-mono">
                ৳{Math.round(monthlySavings).toLocaleString()}
              </span>
            </div>

            {/* Payback period / ROI */}
            <div className="flex items-center justify-between pb-3 border-b border-[#E6E1D8]">
              <div className="flex items-center gap-2 text-sm text-[#5C544D]">
                <Battery className="w-4.5 h-4.5 text-[#8C837A]" />
                <span>{language === 'en' ? 'Payback Period' : 'বিনিয়োগ ফেরত আসার সময়'}</span>
              </div>
              <span className="text-lg font-bold text-[#1F1914] font-mono">
                {model === 'opex' ? (
                  <span className="text-emerald-600 font-bold uppercase text-xs">{language === 'en' ? 'Immediate (Day 1 ROI)' : 'প্রথম দিন থেকেই লাভ'}</span>
                ) : (
                  `${paybackYears.toFixed(1)} ${language === 'en' ? 'Years' : 'বছর'}`
                )}
              </span>
            </div>

            {/* Carbon Offset */}
            <div className="flex items-center justify-between pt-1">
              <div className="flex items-center gap-2 text-sm text-[#5C544D]">
                <Leaf className="w-4.5 h-4.5 text-emerald-500" />
                <span>{language === 'en' ? 'Carbon Offset' : 'কার্বন সাশ্রয়'}</span>
              </div>
              <div className="text-right">
                <span className="text-lg font-bold text-emerald-600 font-mono block">
                  {Math.round(annualCarbonOffset).toLocaleString()} kg/yr
                </span>
                <span className="text-xs text-[#8C837A] font-medium block">
                  {language === 'en' 
                    ? `≈ ${Math.round(equivalentTrees)} trees / year` 
                    : `≈ ${Math.round(equivalentTrees)}টি গাছ / বছর`}
                </span>
              </div>
            </div>
          </div>

          <button className="w-full group/btn relative inline-flex items-center justify-center gap-2 px-6 py-4 rounded-xl bg-primary text-primary-foreground font-bold text-sm transition-all duration-300 hover:bg-primary/95 hover:shadow-lg hover:shadow-primary/20 active:scale-[0.98]">
            <span>{language === 'en' ? 'Book Free Engineering Assessment' : 'ফ্রি ইঞ্জিনিয়ারিং অ্যাসেসমেন্ট বুক করুন'}</span>
            <ArrowRight className="w-4 h-4 group-hover/btn:translate-x-0.5 transition-transform" />
          </button>
        </div>
      </div>
    </div>
  );
}

